### ISSUE TITLE
clang: error: no such file or directory: 'ecdsa_recover/ecdsa_recover.c'

### ISSUE THREAD

**Issue by jorisbontje** [heikoheiko/cy_ecdsa_recover#2]
Since 8e25bdfcefe6081bc0151d13aef1660adef72532 I get this error when installing HydraChain:

```
Installed /private/var/folders/4s/xhntr1m53w3dlq5pm5d42h600000gn/T/easy_install-MVwrs2/ecdsa_recover-0.1.6/.eggs/Cython-0.23.1-py2.7-macosx-10.10-x86_64.egg
clang: error: no such file or directory: 'ecdsa_recover/ecdsa_recover.c'
clang: error: no input files
error: Setup script exited with error: command 'clang' failed with exit status 1
```

Full logs:
https://gist.githubusercontent.com/jorisbontje/c410a8cde95b44a979ff/raw/c97959e3a90fe88240f02bd4fb899efe4ecae04f/hydrachain_install_missing_ecdsa_recover.txt

**Comment by heikoheiko** [comment]
Yes, setuptools version: >18.0 is required. We've not yet found a smooth way to enforce this

**Comment by jorisbontje** [comment]
Ok, works with setuptools-18.3.1
